### ISSUE TITLE
Null strings error

### ISSUE THREAD

**Issue by hiaw** [jkubicek/AutoLocalize#2]
Hi, I would love to get this work. But I'm plagued with null string issues. 

The code works until `line.start_with?("/* ")`. Then it doesn't pass, and hence 0 phrases to translate at the end. Digging into `irb`, I was able to read the file and see that it reads properly, but the line read have `\000` appended to each character. 

For example: `/* Annual License */` appear as `\000/\000*\000 \000A\000n\000n\000u\000a\000l\000 \000L\000i\000c\000e\000n\000s\000e\000 \000*\000/\000\n`

Help? I'm using the built in ruby 1.8.7. I've also tried macruby 1.9.2 but that failed with YAML transform.

**Comment by jkubicek** [comment]
That looks like a string encoding issue.  I'll take a look at it and see if I can figure it out. 

-Jim

**Comment by jkubicek** [comment]
Try messing with line 64 and see if you can find an encoding that works.

```
f = File.open(source_file, "rb:UTF-16LE:UTF-8")
```

**Comment by hiaw** [comment]
I tried with `"rb:UTF-8"`, `"rb:UTF-16"`, `"rb:UTF-16LE"`, `"rb:ASCII"` and they all don't work.

I'll give you the link to my localizable.strings. I'd really appreciate it if you could give it a try. Cheers

http://dl.dropbox.com/u/7607881/Localizable.strings

**Comment by hiaw** [comment]
by the way, I forgot to mention that I tried out the supplied .strings file and it has the same problem as well.
